version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      # Checkout code
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install pylint pycodestyle pydocstyle mypy bandit safety pytest

      # Install shellcheck
      - run:
          name: Install shellcheck
          command: sudo apt-get update && sudo apt-get install -y shellcheck

      # Run linting
      - run:
          name: Run linting
          command: |
            . venv/bin/activate
            PYTHONPATH=. ./tasks/lint.sh

      # Run prediction tests
      - run:
          name: Run prediction tests
          command: |
            . venv/bin/activate
            PYTHONPATH=. pytest -s text_recognizer/tests/test_paragraph_test_recognizer.py

      # Run evaluation tests
      - run:
          name: Run evaluation tests
          command: |
            . venv/bin/activate
            PYTHONPATH=. pytest -s text_recognizer/evaluation/evaluate_paragraph_text_recognizer.py

      # Run training tests
      - run:
          name: Run training tests
          command: |
            . venv/bin/activate
            PYTHONPATH=. bash training/tests/test_run_training.sh

      # Store artifacts (test logs)
      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
